/**
 * Sample data for seeding Daejeon local businesses
 * This represents authentic local places in Daejeon
 */

import { Place } from '../src/lib/types';

export const samplePlaces: Omit<Place, 'id' | 'created_at' | 'updated_at'>[] = [
  // Restaurants
  {
    name: '성심당',
    name_en: 'Sungsimdang',
    category: 'restaurant',
    description: '대전의 대표 빵집이자 레스토랑. 1956년 개업한 역사 깊은 곳으로 튀김소보로와 부추빵이 유명합니다.',
    description_en: 'Daejeon\'s iconic bakery and restaurant established in 1956. Famous for fried soboro bread and chive bread.',
    address: '대전 중구 은행동 145',
    district: '중구',
    coordinates: { lat: 36.3275, lng: 127.4263 },
    image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&h=400&fit=crop',
    features: ['iconic_landmark', 'local_favorite', 'affordable'],
    price_range: 1,
    opening_hours: '08:00-22:00 daily',
    is_local_business: true,
    specialties: [
      { name: 'Fried Soboro Bread', image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=200&h=200&fit=crop' },
      { name: 'Chive Bread', image_url: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=200&h=200&fit=crop' },
      { name: 'Butter Cream Cake', image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=200&h=200&fit=crop' },
    ],
    nearby_attractions: ['Daejeon Station', 'Jungang Market'],
  },
  {
    name: '대전식당',
    name_en: 'Daejeon Sikdang',
    category: 'restaurant',
    description: '1960년대부터 3대째 운영하는 전통 한정식 전문점. 신선한 재료로 만든 계절 반찬이 특징입니다.',
    description_en: 'Traditional Korean fine dining restaurant run by 3 generations since the 1960s. Known for seasonal side dishes with fresh ingredients.',
    address: '대전 중구 선화동 202-5',
    district: '중구',
    image_url: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800&h=400&fit=crop',
    features: ['traditional', 'family_run', 'authentic'],
    price_range: 3,
    opening_hours: '11:00-21:00, Closed Sundays',
    is_local_business: true,
    specialties: [
      { name: 'Korean course meal', image_url: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=200&h=200&fit=crop' },
      { name: 'Seasonal banchan', image_url: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=200&h=200&fit=crop' },
      { name: 'Homemade kimchi', image_url: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=200&h=200&fit=crop' },
    ],
    nearby_attractions: ['Ppuri Park', 'Daejeon Museum of Art'],
  },
  {
    name: '칼국수집 은행골',
    name_en: 'Eunhaenggol Kalguksu',
    category: 'restaurant',
    description: '40년 전통의 칼국수 전문점. 진한 사골육수와 손으로 직접 만든 면이 일품입니다.',
    description_en: '40-year-old traditional noodle restaurant. Famous for rich beef bone broth and handmade noodles.',
    address: '대전 유성구 봉명동 557-3',
    district: '유성구',
    image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&h=400&fit=crop',
    features: ['local_favorite', 'comfort_food', 'family_friendly'],
    price_range: 1,
    opening_hours: '10:00-21:00 daily',
    is_local_business: true,
    specialties: [
      { name: 'Kalguksu (knife-cut noodles)', image_url: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=200&h=200&fit=crop' },
      { name: 'Mandu (dumplings)', image_url: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=200&h=200&fit=crop' },
      { name: 'Bibim-guksu', image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=200&h=200&fit=crop' },
    ],
    nearby_attractions: ['Yuseong Hot Springs', 'Expo Park'],
  },
  {
    name: '대흥동 족발거리',
    name_en: 'Daeheung-dong Jokbal Street',
    category: 'restaurant',
    description: '대전 최고의 족발 거리. 1970년대부터 이어온 족발 전문점들이 모여있습니다.',
    description_en: 'Daejeon\'s best pig trotters street. Multiple specialty restaurants serving jokbal since the 1970s.',
    address: '대전 중구 대흥동',
    district: '중구',
    features: ['local_specialty', 'street_food', 'nightlife'],
    price_range: 2,
    opening_hours: 'Varies by restaurant, most open 16:00-02:00',
    is_local_business: true,
    specialties: [
      { name: 'Jokbal (braised pig trotters)' },
      { name: 'Bossam' },
      { name: 'Soju pairing' },
    ],
    nearby_attractions: ['Daejeon O-World', 'Ppuri Park'],
  },
  {
    name: '이가네떡볶이',
    name_en: 'Igane Tteokbokki',
    category: 'restaurant',
    description: '대전 서구의 숨은 맛집. 매콤달콤한 떡볶이와 튀김이 인기입니다.',
    description_en: 'Hidden gem in Seo-gu. Famous for spicy-sweet tteokbokki and fried foods.',
    address: '대전 서구 둔산동 1234',
    district: '서구',
    features: ['casual', 'affordable', 'student_favorite'],
    price_range: 1,
    opening_hours: '11:00-22:00 daily',
    is_local_business: true,
    specialties: [
      { name: 'Tteokbokki' },
      { name: 'Fried foods' },
      { name: 'Sundae' },
    ],
    nearby_attractions: ['Government Complex Daejeon', 'Hanbat Arboretum'],
  },

  // Cafes
  {
    name: '카페 소소',
    name_en: 'Cafe Soso',
    category: 'cafe',
    description: '한옥을 개조한 감성 카페. 직접 로스팅한 원두와 수제 디저트를 제공합니다.',
    description_en: 'Charming cafe in a renovated traditional Korean house. Serves house-roasted coffee and homemade desserts.',
    address: '대전 중구 은행선화동 103-7',
    district: '중구',
    features: ['traditional_architecture', 'quiet', 'instagram_worthy'],
    price_range: 2,
    opening_hours: '10:00-22:00 daily',
    is_local_business: true,
    specialties: [
      { name: 'Single-origin coffee' },
      { name: 'Seasonal cake' },
      { name: 'Traditional tea' },
    ],
    nearby_attractions: ['Daejeon Station', 'Jungang Market'],
  },
  {
    name: '숲속의 작은 카페',
    name_en: 'Little Cafe in the Forest',
    category: 'cafe',
    description: '계족산 근처 자연 속 카페. 넓은 테라스에서 커피를 즐길 수 있습니다.',
    description_en: 'Nature cafe near Gyejoksan Mountain. Enjoy coffee on a spacious terrace surrounded by trees.',
    address: '대전 대덕구 장동 78-2',
    district: '대덕구',
    features: ['nature_view', 'pet_friendly', 'spacious'],
    price_range: 2,
    opening_hours: '10:00-21:00 daily',
    is_local_business: true,
    specialties: [
      { name: 'Americano' },
      { name: 'Latte art' },
      { name: 'Brunch menu' },
    ],
    nearby_attractions: ['Gyejoksan Mountain', 'Jangtaesan Natural Recreation Forest'],
  },

  // Accommodations
  {
    name: '유성 한옥마을 게스트하우스',
    name_en: 'Yuseong Hanok Village Guesthouse',
    category: 'accommodation',
    description: '전통 한옥 스타일의 게스트하우스. 온천수를 사용한 욕실과 한식 조식을 제공합니다.',
    description_en: 'Traditional hanok-style guesthouse. Features hot spring water bathrooms and Korean breakfast.',
    address: '대전 유성구 봉명동 777',
    district: '유성구',
    features: ['traditional', 'hot_spring', 'breakfast_included'],
    price_range: 2,
    is_local_business: true,
    nearby_attractions: ['Yuseong Hot Springs', 'Expo Park', 'KAIST'],
  },
  {
    name: '대청호반 펜션',
    name_en: 'Daecheongho Lakeside Pension',
    category: 'accommodation',
    description: '대청호 전망이 아름다운 펜션. 가족 단위 여행객에게 적합합니다.',
    description_en: 'Pension with beautiful views of Daecheong Lake. Perfect for families.',
    address: '대전 대덕구 미호동 234-1',
    district: '대덕구',
    features: ['lake_view', 'family_friendly', 'bbq_facilities'],
    price_range: 2,
    is_local_business: true,
    nearby_attractions: ['Daecheong Lake', 'Jangtaesan'],
  },

  // Attractions
  {
    name: '대전 뿌리공원',
    name_en: 'Daejeon Ppuri Park',
    category: 'attraction',
    description: '한국 성씨의 유래를 알 수 있는 독특한 공원. 조각공원과 산책로가 잘 조성되어 있습니다.',
    description_en: 'Unique park showcasing Korean family origins and surnames. Features sculpture gardens and walking trails.',
    address: '대전 중구 뿌리공원로 79',
    district: '중구',
    features: ['cultural', 'walking_trails', 'family_friendly'],
    opening_hours: 'Open 24/7, Museum 09:00-18:00',
    is_local_business: false,
    nearby_attractions: ['Daejeon O-World', 'Sikjang Mountain'],
  },
  {
    name: '한밭수목원',
    name_en: 'Hanbat Arboretum',
    category: 'attraction',
    description: '도심 속 대규모 수목원. 계절마다 다른 꽃과 나무를 감상할 수 있습니다.',
    description_en: 'Large urban arboretum in the city center. Enjoy different flowers and trees each season.',
    address: '대전 서구 둔산대로 169',
    district: '서구',
    features: ['nature', 'free_admission', 'photo_spot'],
    opening_hours: '05:00-22:00 (varies by season)',
    is_local_business: false,
    nearby_attractions: ['Government Complex', 'Expo Bridge'],
  },
  {
    name: '엑스포 과학공원',
    name_en: 'Expo Science Park',
    category: 'attraction',
    description: '1993년 대전 엑스포 개최지. 과학관, 전시장, 공연장 등이 있는 복합 문화 공간입니다.',
    description_en: 'Site of the 1993 Daejeon Expo. Complex cultural space with science museum, exhibitions, and performance halls.',
    address: '대전 유성구 대덕대로 480',
    district: '유성구',
    features: ['educational', 'family_friendly', 'historical'],
    opening_hours: '09:00-18:00, Closed Mondays',
    is_local_business: false,
    nearby_attractions: ['National Science Museum', 'Yuseong Hot Springs'],
  },
  {
    name: '계족산 황톳길',
    name_en: 'Gyejoksan Yellow Soil Trail',
    category: 'attraction',
    description: '맨발로 걸을 수 있는 황톳길. 건강에 좋고 자연을 만끽할 수 있는 트레킹 코스입니다.',
    description_en: 'Barefoot yellow soil trail. Healthy trekking course where you can fully enjoy nature.',
    address: '대전 대덕구 장동산 1-1',
    district: '대덕구',
    features: ['hiking', 'health_trail', 'nature'],
    opening_hours: 'Open 24/7',
    is_local_business: false,
    nearby_attractions: ['Jangtaesan', 'Daecheong Lake'],
  },
];
